name: io_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - matplotlib
  - streamlit
  - pandas
  - numpy
  - pulp
  - networkx
  - plotly
  - graphviz
  - openpyxl
  - pip
  - pip:
    - streamlit-agraph